import json, os
path = os.path.join(os.path.dirname(__file__), '..', 'data', 'market_cap_snapshot.json')
d = json.load(open(path))
total = len(d)
fetched = sum(1 for v in d.values() if v is not None)
large = sum(1 for v in d.values() if v and v >= 10e9)
mega = sum(1 for v in d.values() if v and v >= 200e9)
mid = sum(1 for v in d.values() if v and 2e9 <= v < 10e9)
small = sum(1 for v in d.values() if v and 0.3e9 <= v < 2e9)
micro = sum(1 for v in d.values() if v and v < 0.3e9)
null = sum(1 for v in d.values() if v is None)
print(f"Total tickers:       {total:,}")
print(f"Fetched (non-null):  {fetched:,}  ({fetched/total*100:.1f}%)")
print(f"Null / failed:       {null:,}")
print(f"  Mega  (>=200B):    {mega:,}")
print(f"  Large (10B-200B):  {large:,}")
print(f"  Mid   (2B-10B):    {mid:,}")
print(f"  Small (0.3B-2B):   {small:,}")
print(f"  Micro (<0.3B):     {micro:,}")
